#define SCALE 3/2
#define PLAYER_WIDTH 240*SCALE
#define PLAYER_HEIGHT 518*SCALE
#define THUMBNAIL_SIZE 500
#define MAX_ALBUMS 256
#define ALBUM_HEIGHT 40*SCALE
#define SONG_HEIGHT 30*SCALE
#define PANEL_LEFT_STOP (-PLAYER_WIDTH/2 - 32)
#define PANEL_RIGHT_STOP (PLAYER_WIDTH/2)
#define NBUTTONS 6
#define VISBARS 6
extern float amplitudes[VISBARS];